[package]
name = "tcp-handler"
version = "0.3.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "Conveniently transfer data in chunk through tokio TCP stream."
readme = "README.md"
license = "(MIT OR Apache-2.0) AND BSD-3-Clause"
repository = "https://github.com/xuxiaocheng0201/tcp-handler/"
documentation = "https://docs.rs/tcp-handler/"
categories = ["network-programming"]
keywords = ["tcp", "tokio", "chunk", "io"]

[dependencies]
thiserror = "^1.0"
tokio = { version = "^1", default-features = false, features = ["io-util"] }
bytes = "^1.5"
variable-len-reader = { version = "^1", features = ["bools", "async_default", "async_bools"] }
flate2 = { version = "^1.0", optional = true }
rsa = { version = "~0.9", default-features = false, features = ["std"], optional = true }
aead = { version = "~0.5", default-features = false, features = ["std", "bytes"], optional = true }
aes-gcm = { version = "~0.10", default-features = false, features = ["std", "aes", "rand_core"], optional = true }
sha2 = { version = "~0.10", default-features = false, features = ["std"], optional = true }

[profile.dev.package.num-bigint-dig]
opt-level = 3 # Speed up rsa key gen.

[features]
default = ["auto_flush", "compression", "encrypt"]
auto_flush = []
compression = ["dep:flate2"]
encrypt = ["dep:rsa", "dep:aead", "dep:aes-gcm", "dep:sha2"]

[dev-dependencies]
anyhow = "^1.0"
tokio = { version = "^1", features = ["rt-multi-thread", "macros", "net"] }

[badges]
maintenance = { status = "actively-developed" }
