[package]
name = "tcp-handler"
version = "0.1.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"

[dependencies]
thiserror = "^1.0"
tokio = { version = "^1", default-features = false, features = ["io-util"] }
bytes = "^1.5"
variable-len-reader = { version = "^1", features = ["async_default", "async_bools"] }
rsa = { version = "~0.9", default-features = false, features = ["std"], optional = true }
aes-gcm = { version = "~0.10", default-features = false, features = ["std", "aes", "rand_core"], optional = true }
sha2 = { version = "~0.10", default-features = false, features = ["std"], optional = true }

[profile.dev.package.num-bigint-dig]
opt-level = 3 # Speed up rsa key gen.

[features]
default = ["auto_flush", "encrypt"]
auto_flush = []
encrypt = ["dep:rsa", "dep:aes-gcm", "dep:sha2"]

[dev-dependencies]
anyhow = "^1.0"
tokio = { version = "^1", features = ["rt-multi-thread", "macros", "net"] }

[badges]
maintenance = { status = "actively-developed" }
